---
- name: make config for nginx
  template: src=nginx.conf.j2
            dest={{ kibana_nginx_config_path }}/{{ kibana_nginx_config_name }}
            owner={{ kibana_owner }}
            mode=0644
  notify:
    - reload nginx
